---
- hosts: all 
  become: yes
  tasks:
  - name: install curl
    apt:
      name:
      - curl
      state: latest
      cache_valid_time: 3600
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
 
  - name: UFW
    ufw:     
      state: enabled 
    


